### ISSUE TITLE
Floating-point dates

### ISSUE THREAD

**Issue by laurencelundblade** [sacmwg/draft-ietf-sacm-coswid#18]
In 2.9.4.  The evidence-entry Map, there is a reference to CDDL "time", which by RFC8610 is an int or a float.  The only advantage of float for human time scales is fractions of seconds, and there is burden to support float.

**Comment by henkbirkholz** [comment]
While I see a potential concern with "too much resolution possible", I am very in favor of using tag #6.1 here.

Maybe using an explicit #6.1(int) in the CDDL would be a compromise?

**Comment by laurencelundblade** [comment]
Yes, #6.1(int) seems very good to me.

I assume that if the time is unknown, possibly because the clock was unset, you just leave it out. No need for a special value. Right?

(I wish there was a standard CBOR definition of a time that is #6.1(int) plus some way to indicate very far in the future for use cases that need to express things like no expiration. That is all we need for X.509, EAT and so on. That float is included in #6.1 disrupts this some.)
