### ISSUE TITLE
coswid-extension used but not defined

### ISSUE THREAD

**Issue by thomas-fossati** [sacmwg/draft-ietf-sacm-coswid#24]
The `coswid-extension` CDDL socket is defined in section 2.1 (and 2.8) but never defined.

**Comment by henkbirkholz** [comment]
It is defined in Section 2.2 and elaborated on in 2.3

It is not the only extension point that is not used by the spec itself as it provides a socket for future or custom extensions. Just to be sure we are talking about the same thing: 2.1 is about Character Encoding and 2.8. is about software-meta-entry.

**Comment by thomas-fossati** [comment]
You are right.  Apologies!
