### ISSUE TITLE
wrong CDDL in global-attributes group definition

### ISSUE THREAD

**Issue by thomas-fossati** [sacmwg/draft-ietf-sacm-coswid#25]
In section 2.5 `global-attributes` is defined as
```
   global-attributes = (
     ? lang,
     * any-attribute,
   )
```
Instead, it should be:
```
   global-attributes = (
     ? lang => text,
     * any-attribute,
   )
```
This kind of copy&paste error could be avoided by having one true CDDL source; an example [here](https://github.com/thomas-fossati/draft-psa-token/tree/master/cddl).

**Comment by henkbirkholz** [comment]
Breaking out CDDL should be automated - I absolute agree. There are mechanisms in place for younger I-Ds. I admit that I was too lazy to backport them here. And this is the consequence :-)

**Comment by cabo** [comment]
Please use {::include foo.cddl} and make sure these CDDL files build/validate (write a Makefile).

**Comment by henkbirkholz** [comment]
We currently use:

```
~~~ CDDL
<CODE BEGINS>
{::include concise-swid-tag.cddl}
<CODE ENDS>
~~~
```

But not for the exepositional CDDL fragments that are used to improve readability throughout the text. Using regexp here to extract fragments from the full CDDL usually helps. We did not do this here. The fragments used as examples are not intended to build/validate by their own.

**Comment by henkbirkholz** [comment]
Should be consistent now

**Comment by cabo** [comment]
The XPath expression `//sourcecode[@type='cddl']/text()` can be used on the XML form of this specification to extract the CDDL defined here.

You could make sure that this validates.

**Comment by cabo** [comment]
Oh, can you please commit the referenced cddl files?

**Comment by henkbirkholz** [comment]
done. check-cddl.sh can now be found in the repo
