### ISSUE TITLE
any-uri's type could be uri instead of text

### ISSUE THREAD

**Issue by thomas-fossati** [sacmwg/draft-ietf-sacm-coswid#26]
I am not sure why `any-uri` doesn't use `uri` (`#6.32(tstr)`) from the CDDL preamble instead of `text`?

**Comment by henkbirkholz** [comment]
Thanks!

This is an easy one (and an artifact from the early days). Fixed

**Comment by david-waltermire** [comment]
@henkbirkholz I don't see a commit with a fix yet.
