### ISSUE TITLE
Missing hash description in resource-collection

### ISSUE THREAD

**Issue by thomas-fossati** [sacmwg/draft-ietf-sacm-coswid#28]
There is no description of the `hash` entry in the `resource-collection` group (Section 2.9.2).  Also the CDDL in the same section does not define the `hash` code point.  It is probably better to keep all the relevant bits tightly packed.

**Comment by henkbirkholz** [comment]
It is described in 2.9.1 just before resource-collection. This includes the "code point" and the definition of index 7.

Is your proposal to merge 2.9.1 into 2.9.2? At the moment, I think being next to each other could satisfy the requirement of "relevant bits are tightly packed".

**Comment by thomas-fossati** [comment]
Currently the full information about hash is spread across three different sections - 2.9.1, 2.9.2 and 2.10.

> Is your proposal to merge 2.9.1 into 2.9.2? 

Yep, and also copy `hash = 7` from 2.10 into the "scoped" CDDL.

This is by no means a blocker or anything of that sort.  It's just a suggestion to make the document more easily consumable.  When I implemented it, I was going through each section and build the encoder/decoder from the description, and it all went great until I hit section 2.9.1 :-)

**Comment by henkbirkholz** [comment]
Well... it's hard to argue with that :-)

It's now on the list for the next authors meeting!

**Comment by david-waltermire** [comment]
I consolidated the hash information into the specific section in PR #35.
