### ISSUE TITLE
can't use CDDL to validate seemingly valid CBOR

### ISSUE THREAD

**Issue by thomas-fossati** [sacmwg/draft-ietf-sacm-coswid#29]
If I try to validate the following minimalist (and seemingly valid) `file-entry` using the CDDL provided in the draft:
```
# diag
{ 24: "fw.bin" }

# pretty
a1                 # map(1)
   18 18           # unsigned(24)
   66              # text(6)
      66772e62696e # "fw.bin"
```
I get the following error from the [cddl](https://rubygems.org/gems/cddl) tool:
```
$ cddl file-entry.cddl validate min.cbor
CDDL validation failure (nil for {24=>"fw.bin"}):
["fw.bin", [:prim, 3], nil]
["fw.bin", [:prim, 3], null]
```
This happens because the inlined `any-attribute` consumes all of the map, leaving nothing for `fs-name => text` (this is what the rather cryptic message from the cddl tool is about.)

One could fix this specific bit of CDDL by relocating `global-attributes` to the bottom of `filesystem-item`, but given the pervasiveness of the `global-attributes` group embedding, it's almost certain that similar situations will arise in other places too depending on the relative positioning of the various pieces.

My suggestion would be to make `global-attributes` a map instead, in order remove ambiguities by enforcing tighter namespace segregation.

Note that SWID uses explicit namespacing to cleanly handle these kinds of conflicts.  For example, the following is valid SWID because the `foofoo` extension is explicitly provided under a `tns` namespace:
```
<SoftwareIdentity
  xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd"
  xmlns:tns="http://localhost/foo.xsd"
  name="Roadrunner boot loader"
  tagId="example.acme.roadrunner-sw-bl-v1-0-0"
  version="1.0.0"
  tns:foofoo="bing"
>
[...]
</SoftwareIdentity>
```
Whereas this non-namespaced `foofoo` (closely matching the `any-attribute` philosophy) would fail validation:
```
<SoftwareIdentity
  xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd"
  name="Roadrunner boot loader"
  tagId="example.acme.roadrunner-sw-bl-v1-0-0"
  version="1.0.0"
  foofoo="bong"
>
[...]
</SoftwareIdentity>
```

So more generally it seems to me that the way `global-attributes` are currently handled is way too lax and doesn't reflect the original SWID approach.

**Comment by cabo** [comment]
From a tool perspective, I think having a map with both a catch-all like that provided in global-attributes and an extensible socket like `* $$coswid-extension` in a single map can be problematic even if the order is fixed: extensions not known will then turn up in global-attributes, known extensions in $$coswid-extension, which may or may not be what the application expects.

**Comment by thomas-fossati** [comment]
> From a tool perspective, I think having a map with both a catch-all like that provided in global-attributes and an extensible socket like `* $$coswid-extension` in a single map can be problematic even if the order is fixed: extensions not known will then turn up in global-attributes, known extensions in $$coswid-extension, which may or may not be what the application expects.

I agree, the two extension points (`global-attributes` and the various `-extension` sockets) should be separated.

**Comment by henkbirkholz** [comment]
The proposal discussed between authors is:

separate any-attribute labels from any other labels in maps by using:

```
global-attributes = (
  ? lang => text,
  ? any-attributes = { + any-attribute },
)
```

An alternative and less invasive approach would be to allow all labels in the same map, but moving the "catch all" any-attribute to the end of each map any-attribute occurs in.

Which approach would you prefer?

**Comment by cabo** [comment]
```
  ? any-attributes = { + any-attribute },
```
Syntax.

**Comment by henkbirkholz** [comment]
`? any-attributes => { + any-attribute },`

:o)

**Comment by cabo** [comment]
You need a label number then.

**Comment by henkbirkholz** [comment]
Yes, but first we have to agree on the way forward, just reordering the members of map in a way that global-attributes are always appended to the set would not require a new label. As adding such a global label might shift quite a few labels and impacts implementations, I am very careful here.

**Comment by cabo** [comment]
I'm also a bit more focused on the result than on the way of specifying it -- moving the globals to later in the group sequence might solve this problem already.  You just can't have two catch-alls.

**Comment by henkbirkholz** [comment]
My favored proposal is "just" a reordering, like this:

all defined-label members,
extension-point,
global-attributes,

Implying that extension-points are not to mess with the lang label in global attributes.

**Comment by thomas-fossati** [comment]
> My favored proposal is "just" a reordering, like this:
> 
> all defined-label members,
> extension-point,
> global-attributes,
> 
> Implying that extension-points are not to mess with the lang label in global attributes.

This seems the least invasive solution implementation-wise.  In fact, this has zero impact on my code.

**Comment by david-waltermire** [comment]
@henkbirkholz I don't think this issue has been addressed yet. We should address this now before the spec enters the IESG queue.

The inline CDDL will also need to be updated. Can you take this one?

**Comment by henkbirkholz** [comment]
I might be missing something obvious here, but the inline CDDL addresses the issue like the full CDDL spec.

The inline order is:

```
* stuff
global-attributes
* $$extension-point
```

**Comment by cabo** [comment]
Yes, and that was the problem, as global-attributes contains a catch-all that catches everything before the $$extension-point

**Comment by cabo** [comment]
Why is that catch-all not another extension-point?

**Comment by henkbirkholz** [comment]
oh... thanks, of course. There is a fix for that out there. Will graft another PR from that.

**Comment by henkbirkholz** [comment]
because that might be... less isomorphic to the XSD that literally uses the any attribute.

Do you think it would be more elegant to add another socket? Is there a real world advantage?

**Comment by cabo** [comment]
Right now your CDDL will validate any typo

**Comment by henkbirkholz** [comment]
that is the point. well-defined, well-defined extension, and "the rest" are distinguished. "Careful parsing" can start with "the rest" now. We could discuss mandating the use of a CDDL extension for every single occurring map index, but the agreement was to allow for it.

**Comment by davaya** [comment]
Isn't the point from the original issue that SWID does not accept (non-namespaced) anythings?  The philosophy of writing a security specification that says "I'll accept A, B, C, and anything else" seems like a problem.  Contrary to the ijson approach of allowing anything that isn't prohibited, defining an extension before accepting CoSWIDs that match it seems prudent.

The CDDL will validate not just any typo, but also a megabyte of malware, or for those who remember PKIX, JPEGs of cats.

**Comment by henkbirkholz** [comment]
Well, while I absolutely agree with the concept you illustrated, the ISO provided XSD representing a security specification that allows for that behavior. Quoting from https://standards.iso.org/iso/19770/-2/2015-current/schema.xsd:

```
<xs:anyAttribute namespace="##other" processContents="lax">
<xs:annotation>
<xs:documentation>
Allows any undeclared attributes on any element as long as the attribute is placed in a different namespace.
</xs:documentation>
</xs:annotation>
</xs:anyAttribute>
```

While ##other is required, in the end processContent is lax. That is exactly what we are mapping here in CoSWID.

We can diverge from that and be more strict. I am fine with the idea, but we have to come to consensus.

**Comment by davaya** [comment]
Extensibility can be viewed as error handling: an unrecognized attribute in a normal container is known bad, but in an extension-point container the application can search for a newer version of the same namespace or try to resolve a different namespace,  Successful resolution allows the attribute to be recognized and validated, unsuccessful raises the validation error.

I don't know how XML treats _namespace="##other"_, but it might require the specified namespace to resolve before validation succeeds.

**Comment by davaya** [comment]
My mistake: processContent="lax" does mean that extension schema is not required.  I hope consensus can be obtained on making CoSWID equivalent to "strict".

**Comment by henkbirkholz** [comment]
At the moment it seems that we are steering towards a targeted and concise 2nd WGLC. We'd start such a potential WGLC with a less strict spec definition that maps the "lax" concept in alignment with ISO. One outcome could be that the work here will trigger errata in ISO, but that result is neither implied nor guaranteed. If there are changes to ISO in the future, we can adhere to them and adapt the CoSWID specification. Does that sound feasible?

**Comment by cabo** [comment]
For another view at strict/lax, see 

<https://www.ietf.org/archive/id/draft-ietf-asdf-sdf-02.html#name-formal-syntax-of-sdf>
and
<https://www.ietf.org/archive/id/draft-ietf-asdf-sdf-02.html#name-json-schemaorg-rendition-of>
