### ISSUE TITLE
Top level tagged / untagged

### ISSUE THREAD

**Issue by laurencelundblade** [sacmwg/draft-ietf-sacm-coswid#34]
My understanding in CBOR is that a "tag" is is made up of the tag number ( 1398229316 ) **and** the tag content. From CBORbis:

>    We use the term
>    "tag" for the entire data item consisting of both a tag number and
>    the tag content: the tag content is the data item that is being
>    tagged

In CoSWID the CDDL type concise-swid-tag describes the content. If it was really a tag it would be something more like  concise-swid-tag = #6.1398229316(concise-swid-content) and concise-swid-content would be defined as what concise-swid-tag is.

It also seems like the tagging for COSE-wrapped CoSWIDs could be improved or at least clarified. It should be OK do this: #6.1398229316(#6.18()). If by external means one knows some CBOR is a CoSWID, it should be possible to distinguish whether it is signed or unsigned by wrapping with #6.18(). 

My goal here is to have only one claim in EAT for a CoSWID, rather than EAT having to have separate claims for when a CoSWID is signed or unsigned.

**Comment by henkbirkholz** [comment]
Sections "Signed CoSWID Tags" and "Tagged CoSWID Tags" are now in master

**Comment by henkbirkholz** [comment]
Addressed in master
