### ISSUE TITLE
Ensure cardinalities are in sync with ISO/IEC 19770-2

### ISSUE THREAD

**Issue by david-waltermire** [sacmwg/draft-ietf-sacm-coswid#4]
Some cardinalities are out-of-sync. These need to be reviewed and synced up.

**Comment by henkbirkholz** [comment]
Yes :-)

http://standards.iso.org/iso/19770/-2/2015-current/schema.xsd,
the current ISO text,
and the actual intend the ISO spec authors wanted to convey have to be assessed and aligned in the final draft.

We are close, but I might have introduced a "wishful-thinking" error wrt to payload & evidence quantities in the current CDDL.

The editors should resolve this as soon as possible and provide a candidate for final draft for the next meeting (102).

**Comment by henkbirkholz** [comment]
Every obvious cardinality error seems to be fixed now.

Did I miss something?

**Comment by henkbirkholz** [comment]
Leaving this open to be closed at SACM WG session in BKK.

**Comment by henkbirkholz** [comment]
Addressed
